name: Test & Build

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.18', '1.17' ]
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: '1.13.x'
    - name: Run Static Checks
      run: GOBIN=$PWD/bin go install honnef.co/go/tools/cmd/staticcheck && ./bin/staticcheck ./...
    - name: Run Tests
      run: go test -cover -p 1 -race -mod vendor -v ./...